#!/usr/bin/env bash
private_dns="192.168.0.100"
public_dns="192.168.0.53"
bridge_net="bridge"
internal_net="internal"
root_docker_volume_dir="/mnt/docker"

function check_root_access {
  if [ "$EUID" -ne 0 ]; then
    echo "Please run as root"
    exit
  fi
}
