#!/usr/bin/env bash
source common

container="dns-public"
ip="192.168.0.53"
host_port="65053"
container_port="10000"
image="sameersbn/bind"
version="9.9.5-20170626"
host_data_volume="${root_docker_volume_dir}/dns/public"
container_data_volume="/data"

function run {
  check_root_access

  docker run -d \
   --restart always \
   --name "${container}" \
   --dns 127.0.0.1 \
   --network "${internal_net}" \
   --ip "${ip}" \
   --publish "${host_port}":"${container_port}" \
   --publish 53:53/udp \
   --volume "${host_data_volume}":"${container_data_volume}" \
    "${image}:${version}"

  docker network connect "${bridge_net}" "${container}"
}

command="${1}"
case "${command}" in
  run)
    run
    ;;
  *)
    echo "Unknown command. Available commands: 'run'"
    ;;
esac